PRODUCT_VERSION_MAJOR = 21
PRODUCT_VERSION_MINOR = 0
LINEAGE_BUILDTYPE ?= Community

LINEAGE_VERSION_SUFFIX := Ext-$(LINEAGE_BUILDTYPE)-$(LINEAGE_BUILD)-$(shell date +%Y%m%d-%H%M)

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)
