PRODUCT_VERSION_MAJOR = 22
PRODUCT_VERSION_MINOR = 2
LINEAGE_BUILDTYPE ?= Community

ifeq ($(WITH_GMS),true)
LINEAGE-EXT_VARIANT ?= Gapps
else
LINEAGE-EXT_VARIANT ?= Vanilla
endif

LINEAGE_VERSION_SUFFIX := Ext-$(LINEAGE_BUILDTYPE)-$(LINEAGE_BUILD)-$(LINEAGE-EXT_VARIANT)-$(shell date +%Y%m%d-%H%M)

# Internal version
LINEAGE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_VERSION_SUFFIX)

# Display version
LINEAGE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_VERSION_SUFFIX)

# LineageOS version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.lineage.version=$(LINEAGE_VERSION) \
    ro.lineage.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.lineage.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.lineage.releasetype=$(LINEAGE_BUILDTYPE)
